### ISSUE TITLE
Lesson 10: code unable to be run on the Kovan network

### ISSUE THREAD

**Issue by kristiann57** [PatrickAlphaC/aave_brownie_py_freecode#11]
Hi all, 

I have successfully deployed all the code in lesson 10 (aave borrowing)
however, it is not possible for me to test it on the Kovan network, every single time I try to run the code, it would get stuck, without error nor warning, it would simply not respond. 

After some research, I found ut that it gets stuck when it tries to get the lending pool. for some reason I cannot get it to work. 

I have uploaded the code I used here:
**https://github.com/kristiann57/aave_brownie**

Any help would be greatly appreciated. 

Many thanks

**Comment by PatrickAlphaC** [comment]
Could you ask this question in the full repo? Thanks!

https://github.com/smartcontractkit/full-blockchain-solidity-course-py
