### ISSUE TITLE
TokenBalance, EtherBalance returns undefined

### ISSUE THREAD

**Issue by PrathamGit-dev** [PatrickAlphaC/aave_brownie_py_freecode#14]
![image](https://user-images.githubusercontent.com/96198632/178225383-1a552bc5-29d9-46c6-9f48-ba20a4d14bc7.png)

Although account and address are returned correctly, but calling useTokenBalance and useEtherBalance gives a value undefined.

**Comment by PatrickAlphaC** [comment]
I don't have enough information here. 

Can you follow this guide and come back? https://stackoverflow.com/help/how-to-ask
