### ISSUE TITLE
useEtherBalance and useTokenBalance returns undefined

### ISSUE THREAD

**Issue by PrathamGit-dev** [PatrickAlphaC/aave_brownie_py_freecode#15]
![image](https://user-images.githubusercontent.com/96198632/178421958-b14a296b-670b-42ba-85f2-b340e75465fe.png)

If you look at line 13, the function useTokenBalance should return the amount in the account for that particular token address, but if I check the console, the console gives value undefined and similar for useEtherBalance in line 14. However, account and adress of token is correctly showing up in console. Please suggest a way to correct this.

![image](https://user-images.githubusercontent.com/96198632/178422178-98972e3e-c005-419f-85a2-3780b37516c6.png)

**Comment by PatrickAlphaC** [comment]
I think you might be looking at the wrong repo... This repo uses python not js.

**Comment by PrathamGit-dev** [comment]
Actually, this ia the front end part where we are using useDapp framework.
This is your tutorial on freecodecamp. Please help me with this.
Thanks.
