### ISSUE TITLE
ContractNotFound: No contract deployed at 0xC02aaA39b2...

### ISSUE THREAD

**Issue by Madgeniusblink** [PatrickAlphaC/aave_brownie_py_freecode#5]
Hi!

I am curious to why I get this error when I run it on the mainnet-fork but when I run it on the kovan network my code works...
any idea, should I be on another test net when running "mainnet-fork"?

<img width="909" alt="Screen Shot 2021-12-09 at 5 04 51 PM" src="https://user-images.githubusercontent.com/42707764/145494884-996058cc-e21f-4d39-9d6c-d4eea518cf93.png">

**Comment by PatrickAlphaC** [comment]
Are you using an infura RPC_URL? 

9/10 that's the issue here.

**Comment by PatrickAlphaC** [comment]
Alchemy or Moralis will be much better

**Comment by Madgeniusblink** [comment]
> Alchemy or Moralis will be much better

in order to do this, I have to remove the current mainnet-fork and add the alchemy one correct? Just like we did in the lottery smart contract project?

I added alchemy to the mainnet-fork but now I am getting the following issue -



<img width="777" alt="Screen Shot 2021-12-14 at 12 01 15 AM" src="https://user-images.githubusercontent.com/42707764/145948997-53e72d0a-ca33-4e86-8268-deaed1ff9314.png">

**Comment by PatrickAlphaC** [comment]
Can you actually make this a stack exchange ETH question and tag it brownie? https://ethereum.stackexchange.com/

**Comment by Madgeniusblink** [comment]
will do! thank you!
