### ISSUE TITLE
Withdrawal value

### ISSUE THREAD

**Issue by binhna** [PatrickAlphaC/aave_brownie_py_freecode#8]
Hi Patrick, first of all, thanks for your great work. I've learnt a lot from this.

I have a problem when using withdrawETH of WETHGateway contract in kovan testnet. It works fine on mainnet-fork tho, that's weird.
For example, I deposit 0.5 ETH and then withdraw 0.5 ETH in kovan, sometimes it works, sometimes it doesn't. The error sometimes `ValueError: Execution reverted`, sometimes `ValueError: Gas estimation failed: 'The execution failed due to an exception.'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.`.

But it works fine all the time on mainnet-fork

Another thing is: If I do the following: Deposit (0.5 ETH) -> borrow (say 0.1 ETH) -> repay (all the borrow) -> withdraw (0.5 ETH) ==> this will definitely fail. I have to multiply 0.5 to 0.999 (for example) to make it work. So the question is there anyway that I can calculate the maximum withdrawal value that I can withdraw?

**Comment by PatrickAlphaC** [comment]
Yes. You can do a pull on aave to see how much interest you've accrued. Remember, the instant you borrow some ETH, you start owing more than you borrowed!

**Comment by PatrickAlphaC** [comment]
Closing for now, but feel free to keep the convo going.
