### ISSUE TITLE
No WETH Found

### ISSUE THREAD

**Issue by icalaba** [PatrickAlphaC/aave_brownie_py_freecode#9]
around the timeline in video : 9:02 , when i did mine , i could not find the WETH token in my wallet asset , how can i resolve this ?

**Comment by icalaba** [comment]
i tried adding the custom WETH token using the contract address, but metamask is not adding it either , what do i do ?

**Comment by PatrickAlphaC** [comment]
Could you please ask this in the main repo with screen shots of what you've tried? Thanks!
